/// Ren'Py translation file patcher
///
/// Strategy: clone the structure of an existing translation (e.g. Vietnamese)
/// and replace only the translated text. This guarantees that:
///   - Block IDs (hashes) are identical → Ren'Py can match them
///   - Python blocks (fonts, character defines) are preserved
///   - Voice lines and markup are untouched

use std::collections::HashMap;

/// Generate a complete tl/<lang>/<file>.rpy by cloning a reference tl file
/// and replacing translations with entries from the `translations` map.
///
/// `ref_tl_text`    : raw text of reference tl file (e.g. tl/Vietnamese/script.rpy)
/// `ref_lang`       : language name in reference file (e.g. "Vietnamese")
/// `target_lang`    : language name to output (e.g. "Thai")
/// `translations`   : map of original_english_text → target_translation
/// `char_defines`   : optional character name overrides { var_name → translated_name }
pub fn patch_tl_file(
    ref_tl_text: &str,
    ref_lang: &str,
    target_lang: &str,
    translations: &HashMap<String, String>,
    char_defines: &HashMap<String, String>,
) -> String {
    let mut output = String::new();
    output.push_str(&format!(
        "# Translation: {}\n# Generated by renpy_rs patcher\n\n",
        target_lang
    ));

    // State machine: track whether we're inside a dialogue block
    // so we know when the next quoted string is the translation line
    enum State {
        Normal,
        InDialogBlock { original: String, _has_voice: bool },
        InStringsBlock,
    }

    let mut state = State::Normal;
    let lines: Vec<&str> = ref_tl_text.lines().collect();
    let mut i = 0;

    while i < lines.len() {
        let line = lines[i];

        // Replace language name in translate statements
        let line_out = replace_lang(line, ref_lang, target_lang);

        match &state {
            State::Normal => {
                // Detect: "translate LANG python:"
                if line.contains(&format!("translate {} python:", ref_lang)) {
                    output.push_str(&line_out);
                    output.push('\n');
                    i += 1;
                    continue;
                }

                // Detect: "translate LANG strings:"
                if line.trim() == &format!("translate {} strings:", ref_lang) {
                    output.push_str(&format!("translate {} strings:\n", target_lang));
                    state = State::InStringsBlock;
                    i += 1;
                    continue;
                }

                // Detect: "translate LANG label_HASH:"
                let block_prefix = format!("translate {} ", ref_lang);
                if line.starts_with(&block_prefix) && line.trim_end().ends_with(':') {
                    output.push_str(&line_out);
                    output.push('\n');
                    // Peek: look for the "# original" comment to capture original text
                    // Original is on the comment line: "    # [speaker ]"text""
                    let orig = extract_original_from_block(&lines, i + 1);
                    let has_voice = block_has_voice(&lines, i + 1);
                    state = State::InDialogBlock { original: orig, _has_voice: has_voice };
                    i += 1;
                    continue;
                }

                // Handle define lines with character names
                if line.starts_with("define ") {
                    let patched = patch_define(line, ref_lang, target_lang, char_defines);
                    output.push_str(&patched);
                    output.push('\n');
                    i += 1;
                    continue;
                }

                output.push_str(&line_out);
                output.push('\n');
            }

            State::InDialogBlock { original, _has_voice: _ } => {
                // Comment line: keep as-is (shows original for reference)
                if line.trim_start().starts_with("# ") || line.trim().is_empty() {
                    output.push_str(&line_out);
                    output.push('\n');
                    i += 1;
                    continue;
                }

                // Voice line: keep as-is
                if line.trim_start().starts_with("voice ") {
                    output.push_str(&line_out);
                    output.push('\n');
                    i += 1;
                    continue;
                }

                // Translation line: "    [speaker ]\"old translation\""
                // Replace with our translation
                if let Some((prefix, speaker, _old_text)) = parse_translation_line(line) {
                    let new_text = translations
                        .get(original)
                        .cloned()
                        .unwrap_or_else(|| original.clone());

                    let new_text = if new_text.is_empty() { original.clone() } else { new_text };

                    let new_line = if let Some(spk) = speaker {
                        format!("{}{}  \"{}\"", prefix, spk, escape_rpy(&new_text))
                    } else {
                        format!("{}\"{}\"", prefix, escape_rpy(&new_text))
                    };
                    output.push_str(&new_line);
                    output.push('\n');
                    state = State::Normal;
                    i += 1;
                    continue;
                }

                // Anything else: pass through
                output.push_str(&line_out);
                output.push('\n');
                state = State::Normal;
            }

            State::InStringsBlock => {
                // Blank line: pass through
                if line.trim().is_empty() {
                    output.push('\n');
                    i += 1;
                    continue;
                }

                // End of strings block (new top-level block or EOF)
                if !line.starts_with(' ') && !line.starts_with('\t') {
                    state = State::Normal;
                    // reprocess this line
                    continue;
                }

                // Comment: "    # game/file.rpy:N"
                if line.trim_start().starts_with("# ") {
                    output.push_str(line);
                    output.push('\n');
                    i += 1;
                    continue;
                }

                // old "..." line
                if line.trim_start().starts_with("old \"") {
                    let orig = extract_quoted(line.trim_start().strip_prefix("old ").unwrap_or(""));
                    output.push_str(line);
                    output.push('\n');
                    i += 1;

                    // Next line should be "new ..."  — replace it
                    if i < lines.len() {
                        let next = lines[i];
                        if next.trim_start().starts_with("new \"") {
                            let indent = &next[..next.len() - next.trim_start().len()];
                            let new_text = translations
                                .get(orig)
                                .cloned()
                                .unwrap_or_else(|| orig.to_string());
                            let new_text = if new_text.is_empty() { orig.to_string() } else { new_text };
                            output.push_str(&format!("{}new \"{}\"\n", indent, escape_rpy(&new_text)));
                            i += 1;
                        }
                    }
                    continue;
                }

                output.push_str(line);
                output.push('\n');
            }
        }

        i += 1;
    }

    output
}

// ── helpers ────────────────────────────────────────────────────────────────

fn replace_lang(line: &str, from: &str, to: &str) -> String {
    line.replace(from, to)
}

/// Look ahead from pos to find the "# [speaker ]"original"" comment line
fn extract_original_from_block(lines: &[&str], from: usize) -> String {
    for line in lines.iter().skip(from).take(6) {
        let t = line.trim();
        if t.starts_with("# ") {
            // Strip "# [speaker ]" prefix
            let rest = &t[2..]; // after "# "
            // might be: '"text"' or 'speaker "text"' or 'voice ...'
            if rest.starts_with("voice ") { continue; }
            // Strip optional word before quote
            let text_part = if let Some(idx) = rest.find('"') {
                &rest[idx..]
            } else {
                continue;
            };
            return extract_quoted(text_part).to_string();
        }
    }
    String::new()
}

fn block_has_voice(lines: &[&str], from: usize) -> bool {
    for line in lines.iter().skip(from).take(6) {
        let t = line.trim();
        if t.is_empty() { continue; }
        if t.starts_with("# voice ") { return true; }
        if t.starts_with('#') { continue; }
        break;
    }
    false
}

/// Parse "    [speaker ]\"text\"" → (indent, Option<speaker>, text)
fn parse_translation_line(line: &str) -> Option<(String, Option<String>, String)> {
    let indent_len = line.len() - line.trim_start().len();
    if indent_len == 0 { return None; }
    let indent = line[..indent_len].to_string();
    let rest = line.trim_start();

    // Must start with either a word (speaker) or a quote
    if rest.starts_with('"') {
        let text = extract_quoted(rest);
        return Some((indent, None, text.to_string()));
    }

    // "speaker  \"text\""
    if let Some(q) = rest.find('"') {
        let candidate_spk = rest[q..].trim_start();
        if candidate_spk.starts_with('"') {
            let spk = rest[..q].trim();
            if spk.chars().all(|c| c.is_alphanumeric() || c == '_') && !spk.is_empty() {
                let text = extract_quoted(candidate_spk);
                return Some((indent, Some(spk.to_string()), text.to_string()));
            }
        }
    }

    None
}

/// Extract the string content from `"content"` (handles basic escapes)
fn extract_quoted(s: &str) -> &str {
    let s = s.trim();
    if s.starts_with('"') && s.len() > 1 {
        if let Some(end) = find_closing_quote(s, 1) {
            return &s[1..end];
        }
    }
    s
}

fn find_closing_quote(s: &str, start: usize) -> Option<usize> {
    let bytes = s.as_bytes();
    let mut i = start;
    while i < bytes.len() {
        match bytes[i] {
            b'\\' => { i += 2; } // skip escaped char
            b'"' => return Some(i),
            _ => { i += 1; }
        }
    }
    None
}

/// Escape a string for embedding in Ren'Py quoted string
fn escape_rpy(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Patch a `define X = Character("Name", ...)` line to use translated name
fn patch_define(
    line: &str,
    _ref_lang: &str,
    _target_lang: &str,
    char_defines: &HashMap<String, String>,
) -> String {
    if char_defines.is_empty() { return line.to_string(); }
    for (var, new_name) in char_defines {
        if line.contains(var.as_str()) {
            if let Some(start) = line.find("Character(\"") {
                let after = &line[start + 11..];
                if let Some(end) = after.find('"') {
                    let old_name = &after[..end];
                    return line.replace(
                        &format!("Character(\"{}\"", old_name),
                        &format!("Character(\"{}\"", new_name),
                    );
                }
            }
        }
    }
    line.to_string()
}

/// Build a mapping of original English text → translated text from a list of TextBlocks
pub fn build_translation_map(
    blocks: &[crate::extractor::TextBlock],
) -> HashMap<String, String> {
    blocks
        .iter()
        .filter_map(|b| {
            b.translation.as_ref().map(|t| (b.source.clone(), t.clone()))
        })
        .collect()
}
