# Translation: Thai
# Generated by renpy_rs patcher

# TODO: Translation updated at 2023-08-29 17:43

translate Thai strings:

    # game/ActionEditor.rpy:44
    old "time: [_viewers.time:>.2f] s"
    new "time: [_viewers.time:>.2f] s"

    # game/ActionEditor.rpy:51
    old "default warper"
    new "default warper"

    # game/ActionEditor.rpy:52
    old "rot"
    new "rot"

    # game/ActionEditor.rpy:53
    old "hide"
    new "hide"

    # game/ActionEditor.rpy:56
    old "play"
    new "play"

    # game/ActionEditor.rpy:59
    old "clipboard"
    new "clipboard"

    # game/ActionEditor.rpy:62
    old "close"
    new "close"

    # game/ActionEditor.rpy:65
    old "clear keyframes"
    new "clear keyframes"

    # game/ActionEditor.rpy:66
    old "remove keyframes"
    new "remove keyframes"

    # game/ActionEditor.rpy:67
    old "move keyframes"
    new "move keyframes"

    # game/ActionEditor.rpy:68
    old "last moves"
    new "last moves"

    # game/ActionEditor.rpy:73
    old "Images"
    new "Images"

    # game/ActionEditor.rpy:74
    old "2D Camera"
    new "2D Camera"

    # game/ActionEditor.rpy:75
    old "3D Layers"
    new "3D Layers"

    # game/ActionEditor.rpy:76
    old "3D Camera"
    new "3D Camera"

    # game/ActionEditor.rpy:85
    old "+"
    new "+"

    # game/ActionEditor.rpy:107
    old "Please register 3D layers"
    new "Please register 3D layers"

    # game/ActionEditor.rpy:156
    old "remove"
    new "remove"

    # game/ActionEditor.rpy:158
    old "reset"
    new "reset"

    # game/ActionEditor.rpy:235
    old "Select a warper function"
    new "Select a warper function"

    # game/ActionEditor.rpy:246
    old "add"
    new "add"

    # game/ActionEditor.rpy:273
    old "time: [_viewers.moved_time:>.2f] s"
    new "time: [_viewers.moved_time:>.2f] s"

    # game/ActionEditor.rpy:287
    old "KeyFrames"
    new "KeyFrames"

    # game/ActionEditor.rpy:291
    old "x"
    new "x"

    # game/ActionEditor.rpy:294
    old "[t:>.2f] s"
    new "[t:>.2f] s"

    # game/ActionEditor.rpy:297
    old "loop"
    new "loop"

    # game/ActionEditor.rpy:299
    old "expression"
    new "expression"

    # game/ActionEditor.rpy:300
    old "spline"
    new "spline"

    # game/ActionEditor.rpy:561
    old "Can't open clipboard"
    new "Can't open clipboard"

    # game/ActionEditor.rpy:563
    old "Placed \n\"%s\"\n on clipboard"
    new "Placed \\n\\\"%s\\\"\\n on clipboard"

    # game/ActionEditor.rpy:575
    old "Please type value"
    new "Please type value"

    # game/ActionEditor.rpy:619
    old "Please type image name"
    new "Please type image name"

    # game/ActionEditor.rpy:722
    old "Placed \n'%s'\n on clipboard"
    new "Placed \\n'%s'\\n on clipboard"

    # game/ActionEditor.rpy:891
    old "This isn't a valid expression"
    new "This isn't a valid expression"

    # game/ActionEditor.rpy:1224
    old "Nothing to put"
    new "Nothing to put"

