# Translation: Thai
# Generated by renpy_rs patcher

# TODO: Translation updated at 2023-08-29 17:43

translate Thai strings:

    # game/image_viewer.rpy:31
    old "Type a image name"
    new "Type a image name"

