# Translation: Thai
# Generated by renpy_rs patcher

# TODO: Translation updated at 2023-08-29 17:43

translate Thai strings:

    # game/options.rpy:18
    old "Trapped with Jester"
    new "Trapped with Jester"

