# Translation: Thai
# Generated by renpy_rs patcher

# TODO: Translation updated at 2023-08-29 17:43

translate Thai python:
    gui.system_font = gui.interface_text_font = gui.button_text_font = gui.choice_button_text_font = "DejaVuSans.ttf"
    gui.name_text_font =  "Caudex-Regular.ttf"
    gui.name_text_size = 39

define who2viet = Character("Người lạ", color= '#c4002b',who_outlines=[ (2, "#ffffff") ])
define youviet = Character("Bạn", color= '#c4002b',who_outlines=[ (2, "#ffffff") ])
define manviet = Character("Giọng của người đàn ông", color= '#c4002b',who_outlines=[ (2, "#ffffff") ])
define mannviet = Character("Giọng của người đàn ông khác", color= '#c4002b',who_outlines=[ (2, "#ffffff") ])


# game/script.rpy:129
translate Thai start_5240e499:

    # "Your head hurts..."
    "คุณรู้สึกปวดหัว..."

# game/script.rpy:131
translate Thai start_b4edc1c2:

    # "You feel cold."
    "You feel cold."

# game/script.rpy:133
translate Thai start_da6e8dff:

    # voice "voice/line1.mp3"
    # who "Your highness! Wakey wakey~ Hellooo?"
    voice "voice/line1.mp3"
    who  "Your highness! Wakey wakey~ Hellooo?"

# game/script.rpy:136
translate Thai start_f71d52e9:

    # "That voice... you don’t recognize it."
    "That voice... you don’t recognize it."

# game/script.rpy:138
translate Thai start_f02be0a2:

    # "The last thing you remember-"
    "The last thing you remember-"

# game/script.rpy:140
translate Thai start_997646a4:

    # voice "voice/line2.mp3"
    # who "Hey? Hey? Hey? Are you alive? Are you aliiive yet?"
    voice "voice/line2.mp3"
    who  "Hey? Hey? Hey? Are you alive? Are you aliiive yet?"

# game/script.rpy:143
translate Thai start_a20cefa7:

    # "..."
    "..."

# game/script.rpy:145
translate Thai start_20f31c8f:

    # "What was your name again?"
    "What was your name again?"

# game/script.rpy:147
translate Thai start_8f741bf6:

    # "Everything is a blur."
    "Everything is a blur."

# game/script.rpy:149
translate Thai start_e34481eb:

    # voice "voice/line3.mp3"
    # who "Tell me if yer still dead, c’mon don’t keep me hangin’!"
    voice "voice/line3.mp3"
    who  "Tell me if yer still dead, c’mon don’t keep me hangin’!"

# game/script.rpy:248
translate Thai start_a20cefa7_1:

    # "..."
    "..."

# game/script.rpy:255
translate Thai start_17b5fce2:

    # voice "voice/line4.mp3"
    # who "Oh, yer up. Rise and shine sleepyhead!"
    voice "voice/line4.mp3"
    who  "Oh, yer up. Rise and shine sleepyhead!"

# game/script.rpy:261
translate Thai start_638441b1:

    # voice "voice/line5.mp3"
    # who "I hope I didn’t disturb ya, nyehehehe...!"
    voice "voice/line5.mp3"
    who  "I hope I didn’t disturb ya, nyehehehe...!"

# game/script.rpy:267
translate Thai start_690cb947:

    # voice "voice/line6.mp3"
    # who "Woulda' been a shame if I messed up your sweet slumber~"
    voice "voice/line6.mp3"
    who  "Woulda' been a shame if I messed up your sweet slumber~"

# game/script.rpy:303
translate Thai rude_de9d283d:

    # voice "voice/line7.mp3"
    # who2 "Whoa, someone woke up on the wrong side of the floor!"
    voice "voice/line7.mp3"
    who2viet  "Whoa, someone woke up on the wrong side of the floor!"

# game/script.rpy:309
translate Thai rude_81c2d6a1:

    # voice "voice/line8.mp3"
    # who2 "You’ll grow wrinkly, old and tired and sad all the more quickly if you’re always that kooky n’ crusty!"
    voice "voice/line8.mp3"
    who2viet  "You’ll grow wrinkly, old and tired and sad all the more quickly if you’re always that kooky n’ crusty!"

# game/script.rpy:315
translate Thai rude_4dc57d4d:

    # voice "voice/line9.mp3"
    # who2 "Can’t blame ya when ye’ve been sleepin' on that very sad, cold, hard wood..."
    voice "voice/line9.mp3"
    who2viet  "Can’t blame ya when ye’ve been sleepin' on that very sad, cold, hard wood..."

# game/script.rpy:321
translate Thai rude_a17167b7:

    # "Huh? He's right..."
    "Huh? He's right..."

# game/script.rpy:323
translate Thai rude_c115be88:

    # "Why were you sleeping on the ground?"
    "Why were you sleeping on the ground?"

# game/script.rpy:325
translate Thai rude_95b73fe0:

    # "Actually... you came out of a sack."
    "Actually... you came out of a sack."

# game/script.rpy:338
translate Thai rude_8ace04ad:

    # voice "voice/line10.mp3"
    # who2 "Guess that's whatcha get fer' blind trust."
    voice "voice/line10.mp3"
    who2viet  "Guess that's whatcha get fer' blind trust."

# game/script.rpy:344
translate Thai rude_473edd31:

    # voice "voice/line11.mp3"
    # who2 "Salt and sweeeet betrayal~"
    voice "voice/line11.mp3"
    who2viet  "Salt and sweeeet betrayal~"

# game/script.rpy:350
translate Thai rude_f1e1cb15:

    # "What is he talking about?"
    "What is he talking about?"

# game/script.rpy:356
translate Thai rude_c2504aa6:

    # voice "voice/line12.mp3"
    # who2 "Oh well, once a fool, always a fool!"
    voice "voice/line12.mp3"
    who2viet  "Oh well, once a fool, always a fool!"

# game/script.rpy:362
translate Thai rude_1939486d:

    # "He shrugs."
    "He shrugs."

# game/script.rpy:372
translate Thai angry_e7475e84:

    # you "Who are you calling a fool?!" with hpunch
    youviet  "Who are you calling a fool?!"

# game/script.rpy:376
translate Thai angry_8da05544:

    # voice "voice/line13.mp3"
    # who2 "Hey, didn't say it was you."
    voice "voice/line13.mp3"
    who2viet  "Hey, didn't say it was you."

# game/script.rpy:382
translate Thai angry_e80f5281:

    # "He sighs."
    "He sighs."

# game/script.rpy:386
translate Thai bored_bb78c4b2:

    # voice "voice/line14.mp3"
    voice "voice/line14.mp3"

# game/script.rpy:390
translate Thai bored_e65e1128:

    # who2 "Now I'm bored. Yer borin' me."
    who2viet "Giờ thì tôi chán rồi. Ngài làm tôi chán quá."

# game/script.rpy:394
translate Thai bored_ec9094e6:

    # voice "voice/line15.mp3"
    # who2 "Shoulda' known answering the summons of a prissy noble's gonna be a waste."
    voice "voice/line15.mp3"
    who2viet  "Shoulda' known answering the summons of a prissy noble's gonna be a waste."

# game/script.rpy:406
translate Thai bored_435b1c5d:

    # voice "voice/line16.mp3"
    # who2 "Yer on yer own now."
    voice "voice/line16.mp3"
    who2viet  "Yer on yer own now."

# game/script.rpy:412
translate Thai bored_d1f2e7b7:

    # voice "voice/line17.mp3"
    # who2 "See ya! Dun wanna catch yer royal dullness~"
    voice "voice/line17.mp3"
    who2viet  "See ya! Dun wanna catch yer royal dullness~"

# game/script.rpy:420
translate Thai bored_885356ed:

    # "Before you can put another word in, your vision suddenly starts to go dark."
    "Before you can put another word in, your vision suddenly starts to go dark."

# game/script.rpy:422
translate Thai bored_89ffaa13:

    # "You can't breathe."
    "You can't breathe."

# game/script.rpy:424
translate Thai bored_d1f27f2d:

    # "You can't hear."
    "You can't hear."

# game/script.rpy:426
translate Thai bored_047e271b:

    # "Why? What's happening? What's going on?"
    "Why? What's happening? What's going on?"

# game/script.rpy:428
translate Thai bored_1e80109e:

    # "There's no pain."
    "There's no pain."

# game/script.rpy:430
translate Thai bored_8aad74b8:

    # "-But you know your life is slipping away."
    "-But you know your life is slipping away."

# game/script.rpy:432
translate Thai bored_2f5bc040:

    # "...Just like that, you're gone."
    "...Just like that, you're gone."

# game/script.rpy:462
translate Thai serious_3171c598:

    # voice "voice/line18.mp3"
    # who2 "Dunno. Yer the one who called me."
    voice "voice/line18.mp3"
    who2viet  "Dunno. Yer the one who called me."

# game/script.rpy:473
translate Thai serious_debad1be:

    # voice "voice/line19.mp3"
    voice "voice/line19.mp3"

# game/script.rpy:477
translate Thai serious_3e9c509e:

    # who2 "Wow. S'that how ya treat a guest?"
    who2viet "Chà. Đó là cách ngài đối xử với khách lạ sao?"

# game/script.rpy:481
translate Thai serious_6df99602:

    # voice "voice/line20.mp3"
    # who2 "Ya summoned me here. Meanie."
    voice "voice/line20.mp3"
    who2viet  "Ya summoned me here. Meanie."

# game/script.rpy:487
translate Thai serious_d2ba471e:

    # you "Summoned...?"
    youviet  "Summoned...?"

# game/script.rpy:489
translate Thai serious_830f16cd:

    # voice "voice/line21.mp3"
    voice "voice/line21.mp3"

# game/script.rpy:493
translate Thai serious_eedc343a:

    # who2 "See anyone else here? Nah? Then who else could it be?"
    who2viet "Có thấy ai ở đây nữa không? Không đúng không? Vậy thì còn ai nữa cơ chứ?"

# game/script.rpy:497
translate Thai serious_cad1159a:

    # you "...You're telling me- {b}I{/b} {i}summoned{/i} you?"
    youviet  "...You're telling me- {b}I{/b} {i}summoned{/i} you?"

# game/script.rpy:501
translate Thai serious_63620a0f:

    # voice "voice/line22.mp3"
    # who2 "Did I stutter?"
    voice "voice/line22.mp3"
    who2viet  "Did I stutter?"

# game/script.rpy:515
translate Thai serious_023b6b61:

    # voice "voice/line23.mp3"
    # who2 "A carriage."
    voice "voice/line23.mp3"
    who2viet  "A carriage."

# game/script.rpy:521
translate Thai serious_a474ff96:

    # you "I... can see that."
    youviet  "I... can see that."

# game/script.rpy:525
translate Thai serious_f86a793d:

    # voice "voice/line24.mp3"
    # who2 "Then why do you ask?"
    voice "voice/line24.mp3"
    who2viet  "Then why do you ask?"

# game/script.rpy:531
translate Thai serious_dae0ec55:

    # you "..."
    youviet  "..."

# game/script.rpy:546
translate Thai serious_7102641f:

    # "You smack his face." with hpunch
    "You smack his face."

# game/script.rpy:553
translate Thai serious_55b54d27:

    # voice "voice/line25.mp3"
    # who2 "{b}HEY!{/b} That hurt!"
    voice "voice/line25.mp3"
    who2viet  "{b}HEY!{/b} That hurt!"

# game/script.rpy:558
translate Thai serious_bf1c92ee:

    # voice "voice/line26.mp3"
    # who2 "..."
    voice "voice/line26.mp3"
    who2viet  "..."

# game/script.rpy:572
translate Thai serious_577ed0bc:

    # voice "voice/line27.mp3"
    # who2 "Wowza. Actually, that felt good."
    voice "voice/line27.mp3"
    who2viet  "Wowza. Actually, that felt good."

# game/script.rpy:578
translate Thai serious_3e8c4028:

    # you "Uh-"
    youviet  "Uh-"

# game/script.rpy:582
translate Thai serious_f9e0765f:

    # voice "voice/line28.mp3"
    # who2 "Do that again!" with hpunch
    voice "voice/line28.mp3"
    who2viet  "Do that again!"

# game/script.rpy:588
translate Thai serious_c7660e74:

    # voice "voice/line29.mp3"
    # who2 "... Please?"
    voice "voice/line29.mp3"
    who2viet  "... Please?"

# game/script.rpy:604
translate Thai serious_d69dd625:

    # "... You might have awakened something unfortunate inside him."
    "... You might have awakened something unfortunate inside him."

# game/script.rpy:612
translate Thai serious_b8cc37ea:

    # "You give him a tap on the cheek."
    "You give him a tap on the cheek."

# game/script.rpy:616
translate Thai serious_5f7a38f6:

    # voice "voice/line30.mp3"
    # who2 "Whaaat? That's it?"
    voice "voice/line30.mp3"
    who2viet  "Whaaat? That's it?"

# game/script.rpy:622
translate Thai serious_6700eb86:

    # voice "voice/line31.mp3"
    # who2 "Where's the passion?! The DRAMA?!" with hpunch
    voice "voice/line31.mp3"
    who2viet  "Where's the passion?! The DRAMA?!"

# game/script.rpy:628
translate Thai serious_b0a689b7:

    # you "Uh..."
    youviet  "Uh..."

# game/script.rpy:633
translate Thai serious_4f645476:

    # "You give him another half-hearted tap."
    "You give him another half-hearted tap."

# game/script.rpy:650
translate Thai powa_fcf67626:

    # "You slap him with all your strength!" with hpunch
    "You slap him with all your strength!"

# game/script.rpy:655
translate Thai powa_fb6f0c3f:

    # voice "voice/line32.mp3"
    # who2 "WOOOWHEE! That felt soooo {b}{sc=2}GOOD!{/sc}{/b}"
    voice "voice/line32.mp3"
    who2viet  "WOOOWHEE! That felt soooo {b}{sc=2}GOOD!{/sc}{/b}"

# game/script.rpy:663
translate Thai romance_88467711:

    # voice "voice/line33.mp3"
    # who2 "That's it. I'm forgin' a contract with ya!"
    voice "voice/line33.mp3"
    who2viet  "That's it. I'm forgin' a contract with ya!"

# game/script.rpy:669
translate Thai romance_e4e40429:

    # you "Contract?"
    youviet  "Contract?"

# game/script.rpy:675
translate Thai romance_138dd7d4:

    # voice "voice/line34.mp3"
    # who2 "I ain't interested in yer heart, but-"
    voice "voice/line34.mp3"
    who2viet  "I ain't interested in yer heart, but-"

# game/script.rpy:681
translate Thai romance_6732e4f6:

    # voice "voice/line35.mp3"
    # who2 "I wanna ravish yer soul."
    voice "voice/line35.mp3"
    who2viet  "I wanna ravish yer soul."

# game/script.rpy:687
translate Thai romance_f1740cd8:

    # "He places a hand over his chest and bows."
    "He places a hand over his chest and bows."

# game/script.rpy:691
translate Thai romance_04e1d5eb:

    # voice "voice/line36.mp3"
    # who2 "Jester, Demon of Betrayal and Nightmares at yer service."
    voice "voice/line36.mp3"
    who2viet  "Jester, Demon of Betrayal and Nightmares at yer service."

# game/script.rpy:697
translate Thai romance_d7bb99d5:

    # voice "voice/line37.mp3"
    # who2 "This one shall grant yer deepest desire... {i}master{/i}."
    voice "voice/line37.mp3"
    who2viet  "This one shall grant yer deepest desire... {i}master{/i}."

# game/script.rpy:703
translate Thai romance_ba3a3b7d:

    # "Demon...?"
    "Demon...?"

# game/script.rpy:784
translate Thai memories_466a21b0:

    # "At his words, you felt a sharp sting in your head." with hpunch
    "At his words, you felt a sharp sting in your head."

# game/script.rpy:786
translate Thai memories_f355bc19:

    # "Memories of your demise."
    "Memories of your demise."

# game/script.rpy:788
translate Thai memories_51943ab1:

    # "Betrayed by your closest aide."
    "Betrayed by your closest aide."

# game/script.rpy:790
translate Thai memories_cce49304:

    # "-By your family."
    "-By your family."

# game/script.rpy:792
translate Thai memories_2142f33c:

    # "You have died."
    "You have died."

# game/script.rpy:806
translate Thai memories_2a4b9985:

    # "A strong desire bubbled up from within you- {glitch=10.0}{size=+10}{b}{color=#e30000}{font=HorrorFont-Regular.ttf}REVENGE {/font}{/color}{/b}{/size}{/glitch}"
    "A strong desire bubbled up from within you- {glitch=10.0}{size=+10}{b}{color=#e30000}{font=HorrorFont-Regular.ttf}REVENGE {/font}{/color}{/b}{/size}{/glitch}"

# game/script.rpy:810
translate Thai memories_1eb5fb38:

    # voice "voice/line38.mp3"
    # jester "Aaah... such a beautiful, tainted soul!"
    voice "voice/line38.mp3"
    jester  "Aaah... such a beautiful, tainted soul!"

# game/script.rpy:821
translate Thai memories_8e7a0026:

    # voice "voice/line39.mp3"
    # jester "Come."
    voice "voice/line39.mp3"
    jester  "Come."

# game/script.rpy:826
translate Thai memories_cd94a896:

    # "He stretches out his hand toward you-"
    "He stretches out his hand toward you-"

# game/script.rpy:830
translate Thai memories_dd8be588:

    # voice "voice/line40.mp3"
    # jester "A road to damnation? Or a meaningless death?"
    voice "voice/line40.mp3"
    jester  "A road to damnation? Or a meaningless death?"

# game/script.rpy:834
translate Thai memories_823fc0f6:

    # voice "voice/line41.mp3"
    voice "voice/line41.mp3"

# game/script.rpy:837
translate Thai memories_e4747556:

    # jester "The answer is rather clear-cut, no?"
    jester "Câu trả lời khá là rõ mà, đúng chứ?"

# game/script.rpy:847
translate Thai memories_3fade6b9:

    # "T'was the beginning of a blasphemous partnership..."
    "T'was the beginning of a blasphemous partnership..."

# game/script.rpy:849
translate Thai memories_c2efe065:

    # "A sacrilegious demon and his monarch."
    "A sacrilegious demon and his monarch."

# game/script.rpy:851
translate Thai memories_22957ebf:

    # "Together, they leave destruction and suffering in their wake."
    "Together, they leave destruction and suffering in their wake."

# game/script.rpy:853
translate Thai memories_fce38b6c:

    # "Ah, but what a beautiful symphony of vengeance they create!"
    "Ah, but what a beautiful symphony of vengeance they create!"

# game/script.rpy:883
translate Thai name_d2b9b821:

    # voice "voice/line42.mp3"
    voice "voice/line42.mp3"

# game/script.rpy:886
translate Thai name_1be6e5b6:

    # who2 "Mhm... Guess you can call me Jester. Yup."
    who2viet "Mhm... Ngài có thể gọi tôi là Jester. Yup."

# game/script.rpy:890
translate Thai name_e7c4a758:

    # you "Very well then, Jester-"
    youviet  "Very well then, Jester-"

# game/script.rpy:892
translate Thai name_ac9f2189:

    # you "Who am I?"
    youviet  "Who am I?"

# game/script.rpy:894
translate Thai name_66816b9d:

    # voice "voice/line43.mp3"
    voice "voice/line43.mp3"

# game/script.rpy:897
translate Thai name_d6b214e4:

    # jester "Nyehehehe! {cps=*0.02}...{/cps}No idea."
    jester "Nyehehehe! {cps=*0.02}...{/cps}Tôi chịu."

# game/script.rpy:899
translate Thai name_741fd1c9:

    # voice "voice/line44.mp3"
    voice "voice/line44.mp3"

# game/script.rpy:905
translate Thai name_b17507a0:

    # jester "Ya smelled sooo good, so I came a-buzzin' like a hungry fly!"
    jester "Do ngài thơmmmm quá nên là tôi đã vo ve tìm đến ngài như ruồi đang đói vậy!"

# game/script.rpy:907
translate Thai name_7382748d:

    # voice "voice/line45.mp3"
    voice "voice/line45.mp3"

# game/script.rpy:916
translate Thai name_88374f82:

    # jester "A pure soul corrupted by betrayal is such a rare delicacy."
    jester "Một tâm hồn trong sáng bị vấy bẩn bởi sự phản bội là một đặc sản quý hiếm lắm đó."

# game/script.rpy:920
translate Thai name_c2cc1601:

    # you "Uh-huh..."
    youviet  "Uh-huh..."

# game/script.rpy:922
translate Thai name_262ca0ae:

    # voice "voice/line46.mp3"
    voice "voice/line46.mp3"

# game/script.rpy:925
translate Thai name_375f619b:

    # jester "Ya were seething with so much contempt."
    jester "Khi đó ngài đang sục sôi bởi sự hận thù."

# game/script.rpy:927
translate Thai name_0ed831b7:

    # voice "voice/line47.mp3"
    voice "voice/line47.mp3"

# game/script.rpy:932
translate Thai name_5b67e137:

    # jester "Guess I slurped in too much and took out yer memories along with it... whoops."
    jester "Chắc là ong ruồi tôi đây đã lỡ nhâm nhi ngài nhiều quá nên làm lộ hết kí ức của ngài rồi... whoops."

# game/script.rpy:939
translate Thai name_988d0a3a:

    # you "So, we’re on the same boat here?"
    youviet  "So, we’re on the same boat here?"

# game/script.rpy:941
translate Thai name_b29258f1:

    # voice "voice/line48.mp3"
    voice "voice/line48.mp3"

# game/script.rpy:944
translate Thai name_e30dd1be:

    # who2 "Yep yep! Such a nice boat. Let's keep this ship sailin'!"
    who2viet "Đúng, đúng! Một chiếc thuyền đẹp lắm á. Nên là cứ cho thuyền ra khơi nhé!"

# game/script.rpy:950
translate Thai name_ce9711c8:

    # you "... I don’t understand a word you say."
    youviet  "... I don’t understand a word you say."

# game/script.rpy:953
translate Thai name_f9f3f19c:

    # voice "voice/line49.mp3"
    # who2 "Huh? Am I speaking in the wrong language?"
    voice "voice/line49.mp3"
    who2viet  "Huh? Am I speaking in the wrong language?"

# game/script.rpy:958
translate Thai name_c72f73ad:

    # voice "voice/line50.mp3"
    # who2 "Hello? Konnichiwa? Kamusta? Annyeonghaseyo? Hola?"
    voice "voice/line50.mp3"
    who2viet  "Hello? Konnichiwa? Kamusta? Annyeonghaseyo? Hola?"

# game/script.rpy:964
translate Thai name_6138cdda:

    # you "STOP! I GET IT!" with hpunch
    youviet  "STOP! I GET IT!"

# game/script.rpy:966
translate Thai name_e46e8d39:

    # voice "voice/line51.mp3"
    voice "voice/line51.mp3"

# game/script.rpy:969
translate Thai name_359aa32a:

    # who2 "Aw, how sweet of ya! I'm blushin'."
    who2viet "Aw, ngài dễ thương quá! Làm tôi ngại quá rồi nè."

# game/script.rpy:973
translate Thai name_b97dca40:

    # you "WHY."
    youviet  "WHY."

# game/script.rpy:981
translate Thai name_b7bb3487:

    # voice "voice/line52.mp3"
    voice "voice/line52.mp3"

# game/script.rpy:984
translate Thai name_fc934623:

    # who2 "Whoa! Does that mean the feeling is mutual?!"
    who2viet "Chà! Vậy có nghĩa là tình cảm này xuất phát từ hai phía ư?!"

# game/script.rpy:986
translate Thai name_52cb7551:

    # voice "voice/line53.mp3"
    voice "voice/line53.mp3"

# game/script.rpy:989
translate Thai name_ade24653:

    # who2 "Ya know what that means?"
    who2viet "Ngài biết điều đó có nghĩa là gì không?"

# game/script.rpy:991
translate Thai name_5e17eceb:

    # voice "voice/line54.mp3"
    voice "voice/line54.mp3"

# game/script.rpy:994
translate Thai name_bcc5be7d:

    # who2 "I like ya, bud!"
    who2viet "Tôi thích ngài rồi á!"

# game/script.rpy:1002
translate Thai airhead_0de7f1ec:

    # voice "voice/line55.mp3"
    voice "voice/line55.mp3"

# game/script.rpy:1005
translate Thai airhead_5ef95eed:

    # who2 "Aw, yer quite a chipper ain'tcha?"
    who2viet "Aw, ngài chắc hẳn là tuýp người sôi nổi ấy nhỉ?"

# game/script.rpy:1007
translate Thai airhead_7025e123:

    # voice "voice/line56.mp3"
    voice "voice/line56.mp3"

# game/script.rpy:1010
translate Thai airhead_66231b18:

    # who2 "So cute! I wanna squish your widdle cheeks!"
    who2viet "Dễ thương quá đi! Tôi muốn véo má của ngài ghê!"

# game/script.rpy:1012
translate Thai airhead_6a9730df:

    # voice "voice/line57.mp3"
    voice "voice/line57.mp3"

# game/script.rpy:1015
translate Thai airhead_4296ec94:

    # who2 "I like ya already, nyehehehe!"
    who2viet "Tôi thích ngài rồi đó, nyehehehe!"

# game/script.rpy:1024
translate Thai airhead_a532f7f6:

    # voice "voice/line58.mp3"
    voice "voice/line58.mp3"

# game/script.rpy:1027
translate Thai airhead_a735dea5:

    # who2 "Oh gosh, yer so cuuute!"
    who2viet "Ôi dào, ngài dễ thươnggggg quá!"

# game/script.rpy:1031
translate Thai like_ffbac29c:

    # voice "voice/line59.mp3"
    voice "voice/line59.mp3"

# game/script.rpy:1034
translate Thai like_499fffc8:

    # who2 "Can I take ya home~?"
    who2viet "Tôi có thể đem ngài về nhà chứ~?"

# game/script.rpy:1047
translate Thai like_37a79d58:

    # voice "voice/line60.mp3"
    # who2 "...!" with hpunch
    voice "voice/line60.mp3"
    who2viet  "...!"

# game/script.rpy:1054
translate Thai like_11cd9b64:

    # voice "voice/line61.mp3"
    voice "voice/line61.mp3"

# game/script.rpy:1062
translate Thai like_86190352:

    # who2 "My, how bold!"
    who2viet "Ôi, ngài bạo thật đó!"

# game/script.rpy:1076
translate Thai pet2_bb12a704:

    # voice "voice/line62.mp3"
    # who2 "Oooh, I got it!"
    voice "voice/line62.mp3"
    who2viet  "Oooh, I got it!"

# game/script.rpy:1082
translate Thai pet2_afed4c60:

    # "He totally ignores you."
    "He totally ignores you."

# game/script.rpy:1086
translate Thai pet2_065fd905:

    # voice "voice/line63.mp3"
    voice "voice/line63.mp3"

# game/script.rpy:1094
translate Thai pet2_ad274dcf:

    # who2 "A human pet! How delightful!"
    who2viet "Một thú cưng là con người! Tuyệt làm sao!"

# game/script.rpy:1097
translate Thai pet2_b594b380:

    # voice "voice/line64.mp3"
    # who2 "Never mind our contract then."
    voice "voice/line64.mp3"
    who2viet  "Never mind our contract then."

# game/script.rpy:1105
translate Thai pet2_40cda741:

    # you "What."
    youviet  "What."

# game/script.rpy:1107
translate Thai pet2_deb911ed:

    # voice "voice/line66.mp3"
    voice "voice/line66.mp3"

# game/script.rpy:1110
translate Thai pet2_f1921bef:

    # who2 "Yer comin' with me."
    who2viet "Ngài sẽ đi với tôi."

# game/script.rpy:1114
translate Thai pet2_17fb8e4b:

    # "You try to struggle, but he's far too strong..."
    "You try to struggle, but he's far too strong..."

# game/script.rpy:1116
translate Thai pet2_7a89b02d:

    # voice "voice/line67.mp3"
    voice "voice/line67.mp3"

# game/script.rpy:1119
translate Thai pet2_ef3b3596:

    # who2 "I'll take goooood care of ya, nyehehehe..."
    who2viet "Tôi sẽ chăm sóc ngài thật tốttttt, nyehehehe..."

# game/script.rpy:1151
translate Thai pet2_c402e9ac:

    # "He holds out his hand toward you-"
    "He holds out his hand toward you-"

# game/script.rpy:1155
translate Thai pet2_aab50cb7:

    # voice "voice/line65.mp3"
    # who2 "Shall we~?"
    voice "voice/line65.mp3"
    who2viet  "Shall we~?"

# game/script.rpy:1171
translate Thai pet_22668fcc:

    # "... You realize that you have nowhere else to go."
    "... You realize that you have nowhere else to go."

# game/script.rpy:1173
translate Thai pet_7a9fce1a:

    # "Thus, you take his hand."
    "Thus, you take his hand."

# game/script.rpy:1179
translate Thai pet_38077dc0:

    # "You have no idea where this {i}inhuman{/i} being will take you."
    "You have no idea where this {i}inhuman{/i} being will take you."

# game/script.rpy:1181
translate Thai pet_44572748:

    # "-But certainly, anywhere is better than here... right?"
    "-But certainly, anywhere is better than here... right?"

# game/script.rpy:1213
translate Thai pet_7f32e9fb:

    # you "Where are we?"
    youviet  "Where are we?"

# game/script.rpy:1220
translate Thai jester_98bfb1f1:

    # voice "voice/line68.mp3"
    # who2 "Oh dear. Yer right...!"
    voice "voice/line68.mp3"
    who2viet  "Oh dear. Yer right...!"

# game/script.rpy:1224
translate Thai jester_13933cd2:

    # voice "voice/line69.mp3"
    voice "voice/line69.mp3"

# game/script.rpy:1227
translate Thai jester_925383b8:

    # who2 "How rude of me!"
    who2viet "Tôi thật là thô thiển quá!"

# game/script.rpy:1231
translate Thai jester_5acf9f88:

    # voice "voice/line70.mp3"
    # who2 "Mhm~ well I guess ya can call me Jester!"
    voice "voice/line70.mp3"
    who2viet  "Mhm~ well I guess ya can call me Jester!"

# game/script.rpy:1248
translate Thai romanceend_569628ab:

    # voice "voice/line71.mp3"
    # jester "Pleasure to meet'cha, my dear {i}master{/i}."
    voice "voice/line71.mp3"
    jester  "Pleasure to meet'cha, my dear {i}master{/i}."

# game/script.rpy:1256
translate Thai romanceend_8784cc00:

    # voice "voice/line72.mp3"
    # jester "Now then, my dearest master-"
    voice "voice/line72.mp3"
    jester  "Now then, my dearest master-"

# game/script.rpy:1270
translate Thai romanceend_9de520f3:

    # voice "voice/line73.mp3"
    voice "voice/line73.mp3"

# game/script.rpy:1273
translate Thai romanceend_0154cfa1:

    # jester "Oh? How do ya want me to address ya then?"
    jester "Oh? Ngài muốn tôi gọi ngài như thế nào nè?"

# game/script.rpy:1287
translate Thai romanceend_7f96fc74:

    # voice "voice/line74.mp3"
    # jester "I see... so my [mc] it is."
    voice "voice/line74.mp3"
    jester  "I see... so my [mc] it is."

# game/script.rpy:1296
translate Thai goodend_1560c560:

    # voice "voice/line75.mp3"
    # jester "Well then my dear master, please close yer eyes."
    voice "voice/line75.mp3"
    jester  "Well then my dear master, please close yer eyes."

# game/script.rpy:1303
translate Thai goodend_eff4b609:

    # voice "voice/line76.mp3"
    # jester "Well then my dear [mc], please close yer eyes."
    voice "voice/line76.mp3"
    jester  "Well then my dear [mc], please close yer eyes."

# game/script.rpy:1310
translate Thai goodend_9b024457:

    # "You feel the warmth of his hand over your eyes."
    "You feel the warmth of his hand over your eyes."

# game/script.rpy:1312
translate Thai goodend_314e7057:

    # "The heat lingered even after his palm left your skin."
    "The heat lingered even after his palm left your skin."

# game/script.rpy:1314
translate Thai goodend_346e63a3:

    # voice "voice/line77.mp3"
    # jester "Don't open them now~"
    voice "voice/line77.mp3"
    jester  "Don't open them now~"

# game/script.rpy:1318
translate Thai goodend_f61a8213:

    # "As soon as he whispers those words, his presence disappears."
    "As soon as he whispers those words, his presence disappears."

# game/script.rpy:1320
translate Thai goodend_2294c8bb:

    # voice "voice/man1.mp3"
    # man "Huh? Who are-"
    voice "voice/man1.mp3"
    manviet  "Huh? Who are-"

# game/script.rpy:1324
translate Thai goodend_93820619:

    # "You hear voices from the outside..."
    "You hear voices from the outside..."

# game/script.rpy:1328
translate Thai goodend_da195048:

    # voice "voice/man2.mp3"
    # man "{sc=2}GAAHH...!{/sc}" with hpunch
    voice "voice/man2.mp3"
    manviet  "{sc=2}GAAHH...!{/sc}"

# game/script.rpy:1334
translate Thai goodend_1ab8869d:

    # voice "voice/man3.mp3"
    # mann "M-monster...! No! No...! {sc=2}SPARE ME...!{/sc}" with hpunch
    voice "voice/man3.mp3"
    mannviet  "M-monster...! No! No...! {sc=2}SPARE ME...!{/sc}"

# game/script.rpy:1338
translate Thai goodend_b192475f:

    # voice "voice/line78.mp3"
    # jester "Funny comin' from someone keeping a cadaver at the back~"
    voice "voice/line78.mp3"
    jester  "Funny comin' from someone keeping a cadaver at the back~"

# game/script.rpy:1342
translate Thai goodend_22633401:

    # voice "voice/man4.mp3"
    # mann "W-we were just tasked to dispose of it!"
    voice "voice/man4.mp3"
    mannviet  "W-we were just tasked to dispose of it!"

# game/script.rpy:1346
translate Thai goodend_3740beca:

    # voice "voice/line79.mp3"
    # jester "Do I look like I care~?"
    voice "voice/line79.mp3"
    jester  "Do I look like I care~?"

# game/script.rpy:1352
translate Thai goodend_c4c442a7:

    # voice "voice/man5.mp3"
    # mann "{sc=2}GWAH...!{/sc}" with hpunch
    voice "voice/man5.mp3"
    mannviet  "{sc=2}GWAH...!{/sc}"

# game/script.rpy:1356
translate Thai goodend_a20cefa7:

    # "..."
    "..."

# game/script.rpy:1358
translate Thai goodend_8d53160a:

    # "It's gotten quiet."
    "It's gotten quiet."

# game/script.rpy:1360
translate Thai goodend_42e5bf82:

    # voice "voice/line80.mp3"
    # jester "Open yer eyes dearie~"
    voice "voice/line80.mp3"
    jester  "Open yer eyes dearie~"

# game/script.rpy:1400
translate Thai goodend_07536223:

    # "...!" with hpunch
    "...!"

# game/script.rpy:1402
translate Thai goodend_f7711ded:

    # voice "voice/line81.mp3"
    voice "voice/line81.mp3"

# game/script.rpy:1407
translate Thai goodend_8130a66e:

    # jester "Do ya like it~?"
    jester "Ngài có thích không~?"

# game/script.rpy:1430
translate Thai goodend_808bf229:

    # voice "voice/line82.mp3"
    # jester "Come now, my lovely master."
    voice "voice/line82.mp3"
    jester  "Come now, my lovely master."

# game/script.rpy:1440
translate Thai goodend_d2a63a80:

    # voice "voice/line83.mp3"
    # jester "Come now, my lovely [mc]."
    voice "voice/line83.mp3"
    jester  "Come now, my lovely [mc]."

# game/script.rpy:1445
translate Thai goodend_226ebeab:

    # voice "voice/line84.mp3"
    # jester "Let us raze the world together."
    voice "voice/line84.mp3"
    jester  "Let us raze the world together."

# game/script.rpy:1450
translate Thai goodend_543d286f:

    # voice "voice/line85.mp3"
    voice "voice/line85.mp3"

# game/script.rpy:1453
translate Thai goodend_c8e8d40a:

    # jester "May this be our marriage vow."
    jester "Hãy xem đây là lời thề nguyện trong ngày hôn lễ của chúng ta nhé."

# game/script.rpy:1455
translate Thai goodend_44cba563:

    # voice "voice/line86.mp3"
    voice "voice/line86.mp3"

# game/script.rpy:1459
translate Thai goodend_5e8e79cd:

    # jester "...Until death do us part."
    jester "...Cho đến khi cái chết chia lìa đôi ta."

# game/script.rpy:1522
translate Thai disclaimer_c628b9dc:

    # story "This visual novel was made for a game jam challenge which {b}limited the word count to 1000{/b}.\n\nAll assets were made in one week, with only one sprite, one background, one voice actor, one SFX and one ambient sound."
    story  "This visual novel was made for a game jam challenge which {b}limited the word count to 1000{/b}.\\n\\nAll assets were made in one week, with only one sprite, one background, one voice actor, one SFX and one ambient sound."

# game/script.rpy:1525
translate Thai disclaimer_49040264:

    # nvl clear
    # story "Do you understand?"
    nvl clear
    story "Bạn có rõ không?"

# game/script.rpy:1529
translate Thai disclaimer_76b2fe88:

    # nvl clearNovaSlim-Regular
    nvl clear

translate Thai strings:

    # game/script.rpy:287
    old "{font=NovaSlim-Regular.ttf}{size=+10}'WILL YOU SHUT UP?!'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'WILL YOU SHUT UP?!'{/size}{/font}"

    # game/script.rpy:287
    old "{font=NovaSlim-Regular.ttf}{size=+10}'Where am I?'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'Where am I?'{/size}{/font}"

    # game/script.rpy:287
    old "{font=NovaSlim-Regular.ttf}{size=+10}'Good morning!'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'Good morning!'{/size}{/font}"

    # game/script.rpy:364
    old "{font=NovaSlim-Regular.ttf}{size=+10}Get mad{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}Get mad{/size}{/font}"

    # game/script.rpy:364
    old "{font=NovaSlim-Regular.ttf}{size=+10}Suck it up and ask what's going on{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}Suck it up and ask what's going on{/size}{/font}"

    # game/script.rpy:468
    old "{font=NovaSlim-Regular.ttf}{size=+10}'Answer my question!'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'Answer my question!'{/size}{/font}"

    # game/script.rpy:468
    old "{font=NovaSlim-Regular.ttf}{size=+10}'I see...'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'I see...'{/size}{/font}"

    # game/script.rpy:507
    old "{font=NovaSlim-Regular.ttf}{size=+10}'Then who are you?'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'Then who are you?'{/size}{/font}"

    # game/script.rpy:507
    old "{font=NovaSlim-Regular.ttf}{size=+10}'Then where are we?'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'Then where are we?'{/size}{/font}"

    # game/script.rpy:533
    old "{font=NovaSlim-Regular.ttf}{size=+10}Patience.{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}Patience.{/size}{/font}"

    # game/script.rpy:533
    old "{font=NovaSlim-Regular.ttf}{size=+10}{b}PATIENCE.{/b}{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}{b}PATIENCE.{/b}{/size}{/font}"

    # game/script.rpy:533
    old "{font=NovaSlim-Regular.ttf}{size=+10}Smack him{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}Smack him{/size}{/font}"

    # game/script.rpy:610
    old "{font=NovaSlim-Regular.ttf}{size=+10}Do it{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}Do it{/size}{/font}"

    # game/script.rpy:610
    old "{font=NovaSlim-Regular.ttf}{size=+10}{b}DO IT{/b}{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}{b}DO IT{/b}{/size}{/font}"

    # game/script.rpy:630
    old "{font=NovaSlim-Regular.ttf}{size=+10}Tap again{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}Tap again{/size}{/font}"

    # game/script.rpy:630
    old "{font=NovaSlim-Regular.ttf}{size=+10}FULL POWER{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}FULL POWER{/size}{/font}"

    # game/script.rpy:841
    old "{color=#e30000}{font=HorrorFont-Regular.ttf}{size=+20}Take his hand{/size}{/font}{/color}"
    new "{color=#e30000}{font=HorrorFont-Regular.ttf}{size=+20}Take his hand{/size}{/font}{/color}"

    # game/script.rpy:948
    old "{font=NovaSlim-Regular.ttf}{size=+10}'I don’t get it.'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'I don’t get it.'{/size}{/font}"

    # game/script.rpy:948
    old "{font=NovaSlim-Regular.ttf}{size=+10}'Okay!'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'Okay!'{/size}{/font}"

    # game/script.rpy:1021
    old "{font=NovaSlim-Regular.ttf}{size=+10}'I like you too!'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'I like you too!'{/size}{/font}"

    # game/script.rpy:1021
    old "{font=NovaSlim-Regular.ttf}{size=+10}'More importantly...'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'More importantly...'{/size}{/font}"

    # game/script.rpy:1038
    old "{font=NovaSlim-Regular.ttf}{size=+10}Kiss him instead{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}Kiss him instead{/size}{/font}"

    # game/script.rpy:1038
    old "{font=NovaSlim-Regular.ttf}{size=+10}'Okay! Sure.'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'Okay! Sure.'{/size}{/font}"

    # game/script.rpy:1038
    old "{font=NovaSlim-Regular.ttf}{size=+10}'But we don't even know each other yet!'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'But we don't even know each other yet!'{/size}{/font}"

    # game/script.rpy:1162
    old "{font=NovaSlim-Regular.ttf}{size=+10}Take his hand{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}Take his hand{/size}{/font}"

    # game/script.rpy:1162
    old "{font=NovaSlim-Regular.ttf}{size=+10}...{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}...{/size}{/font}"

    # game/script.rpy:1261
    old "{font=NovaSlim-Regular.ttf}{size=+10}'Master?'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'Master?'{/size}{/font}"

    # game/script.rpy:1261
    old "{font=NovaSlim-Regular.ttf}{size=+10}'Don't call me that...'{/size}{/font}"
    new "{font=NovaSlim-Regular.ttf}{size=+10}'Don't call me that...'{/size}{/font}"

    # game/script.rpy:1531
    old "YES"
    new "YES"

    # game/script.rpy:1531
    old "NO"
    new "NO"
