#include "rpgm_injection_exporter.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonObject>
#include <QTextStream>
#include <QCoreApplication>
#include <QDebug>
#include <iostream>

RpgmInjectionExporter::RpgmInjectionExporter(QObject *parent)
    : QObject(parent)
{
}

bool RpgmInjectionExporter::deploy(const QString &gamePath,
                                    const QMap<QString, QJsonArray> &data,
                                    bool onlyTranslated,
                                    const QString &languageName)
{
    std::cerr << "[NST Injection] Starting injection deploy to: "
              << gamePath.toStdString() << std::endl;

    // 1. Create translation folder
    emit progressUpdated(10, "Creating translation folder...");
    if (!createTranslationFolder(gamePath)) {
        return false;
    }

    QString translationDir = QDir(gamePath).filePath("nst_translations");

    // 2. Write config file
    emit progressUpdated(20, "Writing config...");
    if (!writeConfigFile(translationDir, languageName)) {
        return false;
    }

    // 3. Export each file's translations
    int totalFiles = data.size();
    int processed = 0;

    for (auto it = data.constBegin(); it != data.constEnd(); ++it) {
        const QString &filePath = it.key();
        const QJsonArray &entries = it.value();

        QString baseName = fileBaseName(filePath);
        if (baseName.isEmpty()) {
            processed++;
            continue;
        }

        int pct = 20 + (processed * 60 / qMax(totalFiles, 1));
        emit progressUpdated(pct, QString("Exporting %1...").arg(baseName));

        writeTranslationFile(translationDir, baseName, entries, onlyTranslated);
        processed++;
    }

    // 4. Copy JS plugin
    emit progressUpdated(85, "Copying plugin...");
    if (!copyPluginFile(gamePath)) {
        emit errorOccurred("Failed to copy NST_TranslationLayer.js plugin file.");
        // Non-fatal: user can copy manually
    }

    // 5. Auto-patch plugins.js so end user doesn't need to edit anything
    emit progressUpdated(95, "Patching plugins.js...");
    patchPluginsJs(gamePath);

    emit progressUpdated(100, "Injection deploy complete.");
    std::cerr << "[NST Injection] Deploy complete. "
              << processed << " files exported." << std::endl;
    return true;
}

bool RpgmInjectionExporter::createTranslationFolder(const QString &gamePath)
{
    QDir gameDir(gamePath);
    QString translationPath = gameDir.filePath("nst_translations");

    if (!QDir(translationPath).exists()) {
        if (!QDir().mkpath(translationPath)) {
            emit errorOccurred("Failed to create directory: " + translationPath);
            return false;
        }
    }

    return true;
}

bool RpgmInjectionExporter::writeConfigFile(const QString &translationDir,
                                             const QString &languageName)
{
    QString configPath = QDir(translationDir).filePath("config.txt");
    QFile file(configPath);

    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text)) {
        emit errorOccurred("Failed to write config file: " + configPath);
        return false;
    }

    QTextStream out(&file);

    out << "# NST Translation Layer Configuration\n"
        << "# Generated by NST\n"
        << "\n"
        << "# Enable/disable translation (true/false)\n"
        << "enabled=true\n"
        << "\n"
        << "# Show debug info in F12 console (true/false)\n"
        << "debug=false\n"
        << "\n"
        << "# Load translations lazily per-map (true/false)\n"
        << "lazy_load=true\n"
        << "\n"
        << "# Fallback when no translation found: original / empty / [untranslated]\n"
        << "fallback=original\n"
        << "\n"
        << "# Language name\n"
        << "language_name=" << languageName << "\n";

    file.close();
    return true;
}

bool RpgmInjectionExporter::writeTranslationFile(const QString &translationDir,
                                                   const QString &baseName,
                                                   const QJsonArray &entries,
                                                   bool onlyTranslated)
{
    // Collect entries that have translations
    QList<QPair<QString, QPair<QString, QString>>> translatedEntries;
    // QPair<key, QPair<source, translated>>

    for (const QJsonValue &val : entries) {
        QJsonObject obj = val.toObject();
        QString source = obj["source"].toString();
        QString translated = obj["text"].toString();
        QString key = obj["key"].toString();

        if (source.isEmpty()) continue;
        if (onlyTranslated && translated.isEmpty()) continue;
        if (translated.isEmpty()) continue; // Skip empty translations always

        translatedEntries.append(qMakePair(key, qMakePair(source, translated)));
    }

    if (translatedEntries.isEmpty()) {
        return true; // Nothing to write, skip this file
    }

    QString filePath = QDir(translationDir).filePath(baseName + ".txt");
    QFile file(filePath);

    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text)) {
        emit errorOccurred("Failed to write translation file: " + filePath);
        return false;
    }

    QTextStream out(&file);

    out << "# NST Translation File\n"
        << "# Source: " << baseName << "\n"
        << "# Entries: " << translatedEntries.size() << "\n"
        << "\n";

    for (const auto &entry : translatedEntries) {
        const QString &key = entry.first;
        const QString &source = entry.second.first;
        const QString &translated = entry.second.second;

        // Write key if available
        if (!key.isEmpty()) {
            out << "<<<KEY>>>\n"
                << key << "\n";
        }

        out << "<<<ORIGINAL>>>\n"
            << source << "\n"
            << "<<<TRANSLATED>>>\n"
            << translated << "\n"
            << "<<<END>>>\n"
            << "\n";
    }

    file.close();
    std::cerr << "[NST Injection] Wrote " << translatedEntries.size()
              << " entries to " << baseName.toStdString() << ".txt" << std::endl;
    return true;
}

bool RpgmInjectionExporter::copyPluginFile(const QString &gamePath)
{
    // Determine js/plugins/ path (MV uses www/js/plugins, MZ uses js/plugins)
    QDir gameDir(gamePath);
    QString pluginDir;

    if (gameDir.exists("www/js/plugins")) {
        pluginDir = gameDir.filePath("www/js/plugins");
    } else if (gameDir.exists("js/plugins")) {
        pluginDir = gameDir.filePath("js/plugins");
    } else {
        // Try to create js/plugins
        pluginDir = gameDir.filePath("js/plugins");
        if (!QDir().mkpath(pluginDir)) {
            return false;
        }
    }

    QString destPath = QDir(pluginDir).filePath("NST_TranslationLayer.js");
    QString srcPath = pluginSourcePath();

    // Remove existing copy
    if (QFile::exists(destPath)) {
        QFile::remove(destPath);
    }

    if (QFile::exists(srcPath)) {
        return QFile::copy(srcPath, destPath);
    }

    // If source not found in expected location, try relative to app
    qWarning() << "[NST Injection] Plugin source not found at:" << srcPath;
    return false;
}

void RpgmInjectionExporter::patchPluginsJs(const QString &gamePath)
{
    QDir gameDir(gamePath);

    // Find plugins.js (MV: www/js/plugins.js, MZ: js/plugins.js)
    QString pluginsJsPath;
    if (gameDir.exists("www/js/plugins.js"))
        pluginsJsPath = gameDir.filePath("www/js/plugins.js");
    else if (gameDir.exists("js/plugins.js"))
        pluginsJsPath = gameDir.filePath("js/plugins.js");
    else
        return; // No plugins.js found, skip

    QFile file(pluginsJsPath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return;

    QString content = QString::fromUtf8(file.readAll());
    file.close();

    // Check if already patched
    if (content.contains("NST_TranslationLayer"))
        return;

    // Find the closing bracket of the $plugins array: ];
    // Insert our entry before it
    static const QString entry =
        QStringLiteral("{\"name\":\"NST_TranslationLayer\",\"status\":true,"
                       "\"description\":\"NST Translation Layer\",\"parameters\":{}}");

    int closeBracket = content.lastIndexOf(QStringLiteral("];"));
    if (closeBracket < 0)
        return;

    // Determine if we need a comma (check if there are existing entries)
    QString before = content.left(closeBracket).trimmed();
    bool needComma = !before.isEmpty() && !before.endsWith('[');

    QString insertion = (needComma ? QStringLiteral(",\n") : QStringLiteral("\n"))
                        + entry + QStringLiteral("\n");
    content.insert(closeBracket, insertion);

    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text))
        return;

    file.write(content.toUtf8());
    file.close();

    std::cerr << "[NST Injection] Patched plugins.js" << std::endl;
}

QString RpgmInjectionExporter::fileBaseName(const QString &filePath) const
{
    QFileInfo info(filePath);
    QString name = info.completeBaseName();
    return name;
}

QString RpgmInjectionExporter::pluginSourcePath()
{
    QStringList candidates;
    QString appDir = QCoreApplication::applicationDirPath();

    candidates << appDir + "/Injection/rpgm/NST_TranslationLayer.js"
               << appDir + "/../Injection/rpgm/NST_TranslationLayer.js"
               << appDir + "/../../Injection/rpgm/NST_TranslationLayer.js";

    for (const QString &path : candidates) {
        if (QFile::exists(path)) {
            return QFileInfo(path).absoluteFilePath();
        }
    }

    return candidates.first();
}
